version: "3.1"

services:
  app:
    container_name: express-jwt-auth
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    build: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - express-jwt-app
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    restart: always
    networks:
      - express-jwt-app
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis
    restart: always
    networks:
      - express-jwt-app
    ports:
      - 6379:6379

networks:
  express-jwt-app:
